"use client"
import { useState } from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar";
const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkMode, setDarkMode] = useState(false);

  const toggleDarkMode = () => {
    setDarkMode(prevMode => !prevMode);
  };

  return (
    <html lang="en">
      <body className={`${inter.className} ${darkMode ? 'dark' : 'light'}`}>
      <Navbar />
        <div className="flex justify-end p-4">
          <button onClick={toggleDarkMode} className="px-4 py-2 bg-gray-900 text-white rounded-md shadow-md">
            {darkMode ? "Light Mode" : "Dark Mode"}
          </button>
        </div>
        {children}
      </body>
    </html>
  );
}
